-- DERIVED from app/db/seed.py — regenerate with `python -m app.db.seed --dump-sql`.
-- Not auto-run. Apply manually AFTER `alembic upgrade head` creates the schema.

INSERT INTO products (name, category, short_description, long_description, price, image_url, stock_quantity, weight, colour, use_case, rating, featured) VALUES ('Cloudloop Sport Harness', 'harnesses', 'Featherlight all-day sport harness with cloud-soft leg loops.', 'The Cloudloop is built for long days clipping bolts. A breathable waistbelt spreads load evenly while you hang and project, and the pre-threaded buckle means you''re tied in and climbing in seconds. Four pre-shaped gear loops keep your rack tidy and reachable.', 89.00, '/images/products/cloudloop-sport-harness.webp', 42, 320, 'Chalk Blue', 'sport', 4.7, TRUE)
    ON CONFLICT DO NOTHING;
INSERT INTO products (name, category, short_description, long_description, price, image_url, stock_quantity, weight, colour, use_case, rating, featured) VALUES ('Alpine Gecko Harness', 'harnesses', 'Stripped-back alpine harness that packs down to a fist.', 'When every gram counts, the Alpine Gecko delivers. Ice-clipper slots, adjustable leg loops to fit over big boots, and a packable profile make it the harness you forget you''re wearing on the approach.', 119.00, '/images/products/alpine-gecko-harness.webp', 23, 280, 'Moss Green', 'alpine', 4.8, TRUE)
    ON CONFLICT DO NOTHING;
INSERT INTO products (name, category, short_description, long_description, price, image_url, stock_quantity, weight, colour, use_case, rating, featured) VALUES ('Big Wall Badger Harness', 'harnesses', 'Plush, load-hauling harness for days that turn into nights.', 'Padded like an armchair because you''ll be in it for a while. The Big Wall Badger carries a monster rack, takes a haul line without complaint, and keeps you comfortable through every belay on the route.', 139.00, '/images/products/big-wall-badger-harness.webp', 15, 540, 'Granite Grey', 'big wall', 4.6, FALSE)
    ON CONFLICT DO NOTHING;
INSERT INTO products (name, category, short_description, long_description, price, image_url, stock_quantity, weight, colour, use_case, rating, featured) VALUES ('Indoor Otter Harness', 'harnesses', 'Friendly, hard-wearing harness for gym sessions and first leads.', 'The Otter is the perfect first harness: easy double-back buckles, a comfy fixed-leg fit, and bright colours so you spot your kit in the gear pile. Tough enough to survive years of top-rope laps.', 55.00, '/images/products/indoor-otter-harness.webp', 64, 360, 'Sunset Orange', 'indoor', 4.5, FALSE)
    ON CONFLICT DO NOTHING;
INSERT INTO products (name, category, short_description, long_description, price, image_url, stock_quantity, weight, colour, use_case, rating, featured) VALUES ('Trad Yeti Harness', 'harnesses', 'Five-gear-loop workhorse built to carry a full trad rack.', 'Racks of cams, nuts, slings and screwgates — the Trad Yeti swallows it all across five reinforced gear loops, with a supportive waistbelt that stays comfy on long multi-pitch belays.', 109.00, '/images/products/trad-yeti-harness.webp', 19, 430, 'Ochre', 'trad', 4.7, FALSE)
    ON CONFLICT DO NOTHING;
INSERT INTO products (name, category, short_description, long_description, price, image_url, stock_quantity, weight, colour, use_case, rating, featured) VALUES ('CragGuard Helmet', 'helmets', 'Vented hardshell helmet that shrugs off rockfall and clumsy belayers.', 'A tough ABS shell over an EPS liner soaks up impacts from above and below. Big side vents keep your head cool on sunny pitches, and the dial-fit cradle adjusts one-handed mid-route.', 64.00, '/images/products/cragguard-helmet.webp', 37, 240, 'Cloud White', 'sport', 4.6, TRUE)
    ON CONFLICT DO NOTHING;
INSERT INTO products (name, category, short_description, long_description, price, image_url, stock_quantity, weight, colour, use_case, rating, featured) VALUES ('Summit Shell Helmet', 'helmets', 'Ultralight foam helmet for big alpine days and long approaches.', 'At 195g you''ll barely notice it on the walk-in, but the co-moulded foam construction is serious about protection. Four headlamp clips and a low-profile fit make it the choice for dawn starts.', 79.00, '/images/products/summit-shell-helmet.webp', 21, 195, 'Glacier Blue', 'alpine', 4.8, FALSE)
    ON CONFLICT DO NOTHING;
INSERT INTO products (name, category, short_description, long_description, price, image_url, stock_quantity, weight, colour, use_case, rating, featured) VALUES ('PebbleLite Helmet', 'helmets', 'Budget-friendly all-rounder that''s happy indoors or at the crag.', 'Everything you need and nothing you don''t. The PebbleLite is a comfortable, well-vented hardshell that takes a knock without fuss — ideal as a first lid or a loaner for new partners.', 49.00, '/images/products/pebblelite-helmet.webp', 53, 260, 'Slate', 'indoor', 4.3, FALSE)
    ON CONFLICT DO NOTHING;
INSERT INTO products (name, category, short_description, long_description, price, image_url, stock_quantity, weight, colour, use_case, rating, featured) VALUES ('Sunset 9.8mm Rope', 'ropes', '60m all-rounder single rope with a grippy, durable sheath.', 'A 9.8mm diameter hits the sweet spot between durability and handling — thick enough to project on, supple enough to clip fast. The bi-pattern weave marks the middle so you always find it at the lower-off.', 159.00, '/images/products/sunset-98mm-rope.webp', 28, 4100, 'Sunset Fade', 'sport', 4.9, TRUE)
    ON CONFLICT DO NOTHING;
INSERT INTO products (name, category, short_description, long_description, price, image_url, stock_quantity, weight, colour, use_case, rating, featured) VALUES ('Drycore 9.2mm Alpine Rope', 'ropes', '70m dry-treated skinny single for fast-and-light missions.', 'A full dry treatment on core and sheath sheds water and resists freezing on snowy routes. At 9.2mm it''s light on the rack and feeds smoothly through alpine belay devices when speed matters.', 199.00, '/images/products/drycore-92mm-alpine-rope.webp', 12, 3500, 'Ice White', 'alpine', 4.8, FALSE)
    ON CONFLICT DO NOTHING;
INSERT INTO products (name, category, short_description, long_description, price, image_url, stock_quantity, weight, colour, use_case, rating, featured) VALUES ('Gym Rat 10.2mm Rope', 'ropes', 'Burly 35m gym rope built to survive endless top-rope laps.', 'A thick, hard-wearing 10.2mm sheath laughs off the wear of indoor lowering and auto-belay abuse. The 35m length is perfect for most walls, and the high-vis colour is easy to flake under gym lights.', 109.00, '/images/products/gym-rat-102mm-rope.webp', 34, 4600, 'Volt Yellow', 'indoor', 4.5, FALSE)
    ON CONFLICT DO NOTHING;
INSERT INTO products (name, category, short_description, long_description, price, image_url, stock_quantity, weight, colour, use_case, rating, featured) VALUES ('Featherlock Screwgate', 'carabiners', 'Featherweight screwgate locker for belays and anchors.', 'A keylock nose means no snagging on slings or bolts, and the smooth screwgate sleeve locks with a confident click. At just 48g it''s the carabiner you''ll want a dozen of on your rack.', 14.50, '/images/products/featherlock-screwgate.webp', 120, 48, 'Anodised Violet', 'trad', 4.7, TRUE)
    ON CONFLICT DO NOTHING;
INSERT INTO products (name, category, short_description, long_description, price, image_url, stock_quantity, weight, colour, use_case, rating, featured) VALUES ('TwistLock Belay Biner', 'carabiners', 'Auto-locking HMS pear biner with an anti-cross-load keeper.', 'The twist-lock gate snaps shut automatically so you''re never caught with an open locker. A captive bar keeps the belay device aligned and stops the dreaded cross-load on the gate.', 19.00, '/images/products/twistlock-belay-biner.webp', 88, 72, 'Jet Black', 'sport', 4.6, FALSE)
    ON CONFLICT DO NOTHING;
INSERT INTO products (name, category, short_description, long_description, price, image_url, stock_quantity, weight, colour, use_case, rating, featured) VALUES ('WireGate Quickdraw Set', 'carabiners', 'Six wiregate quickdraws — light, snag-free, ready to send.', 'Wiregate carabiners cut weight and resist gate-flutter on hard clips. This set of six comes with grippy 12cm dogbones and a colour-coded bolt-end biner so you always clip the rope the right way.', 74.00, '/images/products/wiregate-quickdraw-set.webp', 40, 570, 'Mixed Anodised', 'sport', 4.8, FALSE)
    ON CONFLICT DO NOTHING;
INSERT INTO products (name, category, short_description, long_description, price, image_url, stock_quantity, weight, colour, use_case, rating, featured) VALUES ('BombProof HMS Screwgate', 'carabiners', 'Big, burly pear locker for guide-mode belays and rescue rigs.', 'A large basket and high cross-section make the BombProof ideal for Munter hitches, guide-mode belays, and any time you want a locker you can grab with gloves on. Built to outlast the route.', 21.50, '/images/products/bombproof-hms-screwgate.webp', 76, 82, 'Steel Blue', 'alpine', 4.7, FALSE)
    ON CONFLICT DO NOTHING;
